on: [push]

jobs:
  hello_world_job_2:
    runs-on: ubuntu-latest
    name: A job to also say hello and delete later
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-javascript-action@v1
      with:
        who-to-greet: 'Michael'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
